export const BODY_AREAS = [
  { name: 'Abdomen', action: 'abdomen', model: '/3d-model/abdomen_anatomy.glb' },
  { name: 'Abdomen-Pelvis', action: 'abdomen-pelvis' },
  { name: 'Breast', action: 'breast', model: '/3d-model/human_female_breast_anatomy.glb' },
  { name: 'Cardiac', action: 'cardiac', model: '/3d-model/stylizedhumanheart.glb' },
  { name: 'Cardiac-Chest', action: 'cardiac-chest', model: '/3d-model/human_anatomy_heart_in_thorax.glb' },
  { name: 'Cardiac-Chest-Pelvis', action: 'cardiac-chest-pelvis' },
  { name: 'Chest', action: 'chest', model: '/3d-model/chest.glb' },
  { name: 'Chest-Abdomen', action: 'chest-abdomen' },
  { name: 'Chest-Abdomen-Pelvis', action: 'chest-abdomen-pelvis' },
  { name: 'Extremities', action: 'extremities', model: '/3d-model/arms_hands_head_legs_and_feet__low_poly_female.glb' },
  { name: 'Head', action: 'head', model: '/3d-model/head_study.glb' },
  { name: 'Head-Neck', action: 'head-neck', model: '/3d-model/head_neck.glb' },
  { name: 'Head-Neck-Chest-Abdomen', action: 'head-neck-chest-abdomen' },
  { name: 'Head-Spine', action: 'head-spine', model: '/3d-model/the_human_spinal_column.glb' },
  { name: 'Lower Extremity', action: 'lower extremity' },
  { name: 'Maxface', action: 'maxface', model: '/3d-model/maxface.glb' },
  { name: 'Neck', action: 'neck', model: '/3d-model/neck.glb' },
  { name: 'Neck-Chest', action: 'neck-chest' },
  { name: 'Neck-Chest-Abdomen-Pelvis', action: 'neck-chest-abdomen-pelvis' },
  { name: 'Pelvis', action: 'pelvis', model: '/3d-model/VH_F_Pelvis.glb' },
  { name: 'Spine', action: 'spine', model: '/3d-model/the_human_spinal_column.glb' },
  { name: 'Spine-Pelvis', action: 'spine-pelvis' },
  { name: 'Unspecified', action: 'unspecified', model: '/3d-model/unspecified.glb' },
  { name: 'Upper Extremity', action: 'upper extremity' }
];
